# Site wide configuration

title:            jiekebo.info
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Jacob Salomonsen
  avatar: https://s.gravatar.com/avatar/d040926f01de509a00065e87b0019daa?s=200
  bio: ""
  email: jiekebo@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-58988834-1
    verify: sWAOsMHH0tKaJBihCFj5BsGZ1xVOYuUW-8lAQTA3uEE
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: jiekebo
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: jiekebo
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

collections:
  projects:
    output: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
